import os
END_POINT_SHEETY = os.environ.get('END_POINT_SHEETY')
# print(END_POINT_SHEETY)
AUTHORIZATION_SHEETY = os.environ.get('AUTHORIZATION_SHEETY')
# print(AUTHORIZATION_SHEETY)
APP_KEY_TEQ = os.environ.get('APP_KEY_TEQ')
# print(APP_KEY_TEQ)

